<a href="https://colab.research.google.com/github/albaMCh/Pandas/blob/main/Proyecto_final_Pandas_III.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

En este proyecto vamos a trabajar con otro de los datasets más usados para aprender, contiene datos de las 1000 películas mejor valoradas segun IMDB.

La siguiente url contienen el csv para crear el dataframe : https://raw.githubusercontent.com/thechaudharysab/imdb-data-pandas-visualization/master/data/imdb_1000.csv

Puedes usar la url directamente para crear el dataframe.

In [ ]:
movies = pd.read_csv('https://raw.githubusercontent.com/thechaudharysab/imdb-data-pandas-visualization/master/data/imdb_1000.csv')

Comprueba las 5 primeras filas para confirmar que el moviesframe se ha creado correctamente.

In [ ]:
movies.head(5)

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

#Ejercicio 1

Almacena en la variable solucion_1 el número de filas y en la variable solucion_1b el número de columnas.

In [ ]:
solucion_1=len(movies.index)

solucion_1b= len(movies.columns)

#Ejercicio 2

Almacena en la variable solucion_2 las 10 primeras filas del dataframe ordenado según la duración de las películas de más corta a más larga.

In [ ]:
solucion_2= movies.sort_values(by='duration',ascending=True).head(10)


solucion_2

,star_rating,title,content_rating,genre,duration,actors_list
389,8.0,Freaks,UNRATED,Drama,64,"[u'Wallace Ford', u'Leila Hyams', u'Olga Bacla..."
338,8.0,Battleship Potemkin,UNRATED,History,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
258,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"[u'Werner Krauss', u'Conrad Veidt', u'Friedric..."
293,8.1,Duck Soup,PASSED,Comedy,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
88,8.4,The Kid,NOT RATED,Comedy,68,"[u'Charles Chaplin', u'Edna Purviance', u'Jack..."
742,7.6,Following,R,Mystery,69,"[u'Jeremy Theobald', u'Alex Haw', u'Lucy Russe..."
351,8.0,Frankenstein,UNRATED,Horror,70,"[u'Colin Clive', u'Mae Clarke', u'Boris Karloff']"
938,7.4,Alice in Wonderland,G,Animation,75,"[u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha..."
405,7.9,The Bride of Frankenstein,NOT RATED,Horror,75,"[u'Boris Karloff', u'Elsa Lanchester', u'Colin..."
303,8.0,The Nightmare Before Christmas,PG,Animation,76,"[u'Danny Elfman', u'Chris Sarandon', u""Catheri..."

#Ejercicio 3

Comprueba cuantos valores faltan en cada columna

In [ ]:
movies.isnull().sum()

star_rating       0
title             0
content_rating    3
genre             0
duration          0
actors_list       0
dtype: int64

Almacena en la variable solucion_3 las filas donde faltan valores.

In [ ]:
solucion_3= movies[movies.isna().any(axis=1)]

solucion_3

,star_rating,title,content_rating,genre,duration,actors_list
187,8.2,Butch Cassidy and the Sundance Kid,NaN,Biography,110,"[u'Paul Newman', u'Robert Redford', u'Katharin..."
649,7.7,Where Eagles Dare,NaN,Action,158,"[u'Richard Burton', u'Clint Eastwood', u'Mary ..."
936,7.4,True Grit,NaN,Adventure,128,"[u'John Wayne', u'Kim Darby', u'Glen Campbell']"

#Ejercicio 4

Compara la media de estrellas en las películas que duran dos horas o más frente a las que duran menos de dos horas. 

Almacena en la variable solucion_4 la media de estrellas mayor, redondeada a dos decimales.

In [ ]:
mas_2h = movies[(movies['duration']>=120)]['star_rating'].mean()
menos_2h = movies[(movies['duration']<120)]['star_rating'].mean()

In [ ]:
solucion_4=(mas_2h if mas_2h > menos_2h else menos_2h).round(2)

solucion_4

7.95

#Ejercicio 5

Calcula la duración media para cada género. Almacena como cadena de  texto en la variable solucion_5 el género con la media de duración más baja.

In [ ]:
movies.groupby('genre')['duration'].mean()

genre
Action       126.485294
Adventure    134.840000
Animation     96.596774
Biography    131.844156
Comedy       107.602564
Crime        122.298387
Drama        126.539568
Family       107.500000
Fantasy      112.000000
Film-Noir     97.333333
History       66.000000
Horror       102.517241
Mystery      115.625000
Sci-Fi       109.000000
Thriller     114.200000
Western      136.666667
Name: duration, dtype: float64

Escribe tu respuesta como número entero en la variable solucion_4

In [ ]:
solucion_5=movies.groupby('genre')['duration'].mean().idxmin()
solucion_5

'History'

# Ejercicio 6

Almacena en la variable solucion_6 el dataframe resultante de buscar la pelicula con mayor puntuación de estrellas para cada género.

In [ ]:
sorted_movies=movies.sort_values(by='star_rating',ascending=False)
solucion_6=sorted_movies.groupby(['genre'])[['title','star_rating']].first()

solucion_6

                                                   title  star_rating
genre
Action                                   The Dark Knight          9.0
Adventure  The Lord of the Rings: The Return of the King          8.9
Animation                                  Spirited Away          8.6
Biography                               Schindler's List          8.9
Comedy                                      Modern Times          8.6
Crime                           The Shawshank Redemption          9.3
Drama                                       12 Angry Men          8.9
Family                        E.T. the Extra-Terrestrial          7.9
Fantasy                        The City of Lost Children          7.7
Film-Noir                                  The Third Man          8.3
History                              Battleship Potemkin          8.0
Horror                                            Psycho          8.6
Mystery                                      Rear Window          8.6
Sci-Fi                                      Blade Runner          8.2
Thriller                               Shadow of a Doubt          8.0
Western                   The Good, the Bad and the Ugly          8.9

#Ejercicio 7

Comprueba si existen películas con el mismo título. Y de ser así ¿Alguna está duplicada por error? Responde esta pregunta con un booleano en la variable solucion_7

In [ ]:
result = movies[movies['title'].duplicated(keep=False)].sort_values(by='title')

result

,star_rating,title,content_rating,genre,duration,actors_list
703,7.6,Dracula,APPROVED,Horror,85,"[u'Bela Lugosi', u'Helen Chandler', u'David Ma..."
905,7.5,Dracula,R,Horror,128,"[u'Gary Oldman', u'Winona Ryder', u'Anthony Ho..."
678,7.7,Les Miserables,PG-13,Drama,158,"[u'Hugh Jackman', u'Russell Crowe', u'Anne Hat..."
924,7.5,Les Miserables,PG-13,Crime,134,"[u'Liam Neeson', u'Geoffrey Rush', u'Uma Thurm..."
466,7.9,The Girl with the Dragon Tattoo,R,Crime,158,"[u'Daniel Craig', u'Rooney Mara', u'Christophe..."
482,7.8,The Girl with the Dragon Tattoo,R,Crime,152,"[u'Michael Nyqvist', u'Noomi Rapace', u'Ewa Fr..."
662,7.7,True Grit,PG-13,Adventure,110,"[u'Jeff Bridges', u'Matt Damon', u'Hailee Stei..."
936,7.4,True Grit,NaN,Adventure,128,"[u'John Wayne', u'Kim Darby', u'Glen Campbell']"

In [ ]:
solucion_7= False

# Ejercicio Extra.

Crea un diccionario 'actor_dict' cuya clave sea el nombre de los actores y su valor el número de películas del dataframe donde aparece. Ordenalo de mayor a menor según el número de películas en las que aparece el actor/actriz.

**Pista: ten en cuenta que antes de crear el diccionario deberas tratar los datos de la columna 'actor_list'**

In [ ]:
import operator
import re

actors_list=[]
unique_actors_list=[]
unique_movies_count=[]
actors=movies['actors_list']

for i in range(len(actors)):
  lst=re.sub(r"\b' u'\b", '',actors[i])
  lst=re.sub(r"\[u\b", '',lst)
  lst=lst.replace('[u','')
  lst=lst.replace(']','')
  lst=lst.replace(' u','')
  lst=lst.replace('"','')
  lst=lst.split(',')
  for y in lst:
    y=y.lstrip("\'")
    y=y.rstrip("\'")
    actors_list.append(y)
actors_list

for item in actors_list:
    if item not in unique_actors_list:
        unique_actors_list.append(item)

for actor in unique_actors_list:
  unique_movies_count.append(actors_list.count(actor))


actor_dict = dict(zip(unique_actors_list, unique_movies_count))

actor_dict = sorted(actor_dict.items(), key=operator.itemgetter(1), reverse=True)
actor_dict









actor_dict

[('Robert De Niro', 18),
 ('Clint Eastwood', 14),
 ('Brad Pitt', 14),
 ('Tom Hanks', 14),
 ('Al Pacino', 13),
 ('Johnny Depp', 12),
 ('Christian Bale', 11),
 ('Leonardo DiCaprio', 11),
 ('Dustin Hoffman', 11),
 ('Harrison Ford', 10),
 ('James Stewart', 10),
 ('Julianne Moore', 10),
 ('Denzel Washington', 10),
 ('Jack Nicholson', 9),
 ('Russell Crowe', 9),
 ('Sean Connery', 9),
 ('Ed Harris', 9),
 ('Ethan Hawke', 9),
 ('Morgan Freeman', 8),
 ('Ian McKellen', 8),
 ('Matt Damon', 8),
 ('Cary Grant', 8),
 ('Kate Winslet', 8),
 ('Michael Caine', 8),
 ('Bruce Willis', 8),
 ('Robert Downey Jr.', 8),
 ('Jake Gyllenhaal', 8),
 ('Tom Cruise', 8),
 ('Sean Penn', 8),
 ('Robert Duvall', 7),
 ('Ralph Fiennes', 7),
 ('Edward Norton', 7),
 ('Humphrey Bogart', 7),
 ('Scarlett Johansson', 7),
 ('Jennifer Connelly', 7),
 ('Tony Chiu Wai Leung', 7),
 ('Daniel Radcliffe', 7),
 ('Emma Watson', 7),
 ('Rupert Grint', 7),
 ('Geoffrey Rush', 7),
 ('Cate Blanchett', 7),
 ('Meryl Streep', 7),
 ('Samuel L. Jackson', 6),
 ('Joseph Gordon-Levitt', 6),
 ('Kevin Spacey', 6),
 ('Anthony Hopkins', 6),
 ('William Holden', 6),
 ('Hugh Jackman', 6),
 ('Gene Hackman', 6),
 ('John Goodman', 6),
 ('Ewan McGregor', 6),
 ('Daniel Day-Lewis', 6),
 ('Woody Allen', 6),
 ('John Wayne', 6),
 ('Kevin Costner', 6),
 ('George Clooney', 6),
 ('Nicolas Cage', 6),
 ('Tim Robbins', 5),
 ('Uma Thurman', 5),
 ('Elijah Wood', 5),
 ('Liam Neeson', 5),
 ('Joe Pesci', 5),
 ('Gary Oldman', 5),
 ('Natalie Portman', 5),
 ('Charles Chaplin', 5),
 ('Guy Pearce', 5),
 ('Aamir Khan', 5),
 ('Sigourney Weaver', 5),
 ('Harvey Keitel', 5),
 ('Paul Newman', 5),
 ('Robert Redford', 5),
 ('Robin Williams', 5),
 ('Philip Seymour Hoffman', 5),
 ('Joan Allen', 5),
 ('Frances McDormand', 5),
 ('Willem Dafoe', 5),
 ('Gael Garc\\xeda Bernal', 5),
 ('Julie Delpy', 5),
 ('Audrey Hepburn', 5),
 ('Bill Murray', 5),
 ('Naomi Watts', 5),
 ('Emma Thompson', 5),
 ('Steve Carell', 5),
 ('Alec Baldwin', 5),
 ('Michael Douglas', 5),
 ('Marlon Brando', 4),
 ('Viggo Mortensen', 4),
 ('Ben Kingsley', 4),
 ('Helena Bonham Carter', 4),
 ('Carrie Fisher', 4),
 ('Matthew McConaughey', 4),
 ('Jodie Foster', 4),
 ('Grace Kelly', 4),
 ('Joaquin Phoenix', 4),
 ('Arnold Schwarzenegger', 4),
 ('Christopher Lloyd', 4),
 ('Jamie Foxx', 4),
 ('Mel Gibson', 4),
 ('Gregory Peck', 4),
 ('Jared Leto', 4),
 ('John Cleese', 4),
 ('Jack Lemmon', 4),
 ('Benicio Del Toro', 4),
 ('Steve McQueen', 4),
 ('Faye Dunaway', 4),
 ('Ben Affleck', 4),
 ('Laurence Olivier', 4),
 ('Jeff Bridges', 4),
 ('Gerard Butler', 4),
 ('Toni Collette', 4),
 ('Charlton Heston', 4),
 ('Kurt Russell', 4),
 ('Bradley Cooper', 4),
 ('Javier Bardem', 4),
 ('Chiwetel Ejiofor', 4),
 ('Diane Keaton', 4),
 ('Keira Knightley', 4),
 ('Patrick Stewart', 4),
 ('Katharine Hepburn', 4),
 ('Gene Wilder', 4),
 ('Nicole Kidman', 4),
 ('Catherine Deneuve', 4),
 ('Christopher Plummer', 4),
 ('Martin Freeman', 4),
 ('Mia Farrow', 4),
 ('Kevin Bacon', 4),
 ('Daniel Craig', 4),
 ('Dan Aykroyd', 4),
 ('Bill Paxton', 4),
 ('Rachel McAdams', 4),
 ('Franka Potente', 4),
 ('John Malkovich', 4),
 ('Emily Watson', 4),
 ('John Turturro', 4),
 ('Cameron Diaz', 4),
 ('Jude Law', 4),
 ('John Cusack', 4),
 ('Tobey Maguire', 4),
 ('Kevin Kline', 4),
 ('Vera Farmiga', 4),
 ('Henry Fonda', 3),
 ('Mark Hamill', 3),
 ('Robin Wright', 3),
 ('Anne Hathaway', 3),
 ('Jessica Chastain', 3),
 ('Toshir\\xf4 Mifune', 3),
 ('Keanu Reeves', 3),
 ('Chazz Palminteri', 3),
 ('Charles Bronson', 3),
 ('Ingrid Bergman', 3),
 ("Beverly D'Angelo", 3),
 ('Janet Leigh', 3),
 ('Vera Miles', 3),
 ('Peter Sellers', 3),
 ('Michael J. Fox', 3),
 ('Matthew Broderick', 3),
 ('Jeremy Irons', 3),
 ('Orson Welles', 3),
 ('Joseph Cotten', 3),
 ('Michael Biehn', 3),
 ('Min-sik Choi', 3),
 ('Tim Allen', 3),
 ('Shah Rukh Khan', 3),
 ('Tim Roth', 3),
 ('Michael Madsen', 3),
 ('Jim Carrey', 3),
 ('Robert Shaw', 3),
 ('Shirley MacLaine', 3),
 ('Ken Watanabe', 3),
 ('Michelle Pfeiffer', 3),
 ('Mads Mikkelsen', 3),
 ('Bruno Ganz', 3),
 ('Spencer Tracy', 3),
 ('Val Kilmer', 3),
 ('Jack Hawkins', 3),
 ('Alan Rickman', 3),
 ('Jonah Hill', 3),
 ('Emile Hirsch', 3),
 ('Catherine Keener', 3),
 ('Christopher Walken', 3),
 ('John Cazale', 3),
 ('Richard Gere', 3),
 ('Cary Elwes', 3),
 ('Don Cheadle', 3),
 ('Colin Firth', 3),
 ('Chris Pratt', 3),
 ('Tommy Lee Jones', 3),
 ('Josh Brolin', 3),
 ('Clive Owen', 3),
 ('Richard Burton', 3),
 ('Patricia Arquette', 3),
 ('Hilary Swank', 3),
 ('Mark Ruffalo', 3),
 ('Lauren Bacall', 3),
 ('Roy Scheider', 3),
 ('Richard Dreyfuss', 3),
 ('Marie-Jos\\xe9e Croze', 3),
 ('Billy Bob Thornton', 3),
 ('Laura Linney', 3),
 ('Laura Dern', 3),
 ('Gena Rowlands', 3),
 ('Simon Pegg', 3),
 ('Sissy Spacek', 3),
 ('Amy Adams', 3),
 ('Julie Christie', 3),
 ('Sam Shepard', 3),
 ('Nick Frost', 3),
 ('Brenda Blethyn', 3),
 ('Richard Armitage', 3),
 ('Dennis Hopper', 3),
 ('Dianne Wiest', 3),
 ('Holly Hunter', 3),
 ('Winona Ryder', 3),
 ('Judi Dench', 3),
 ('Michael Keaton', 3),
 ('Yun-Fat Chow', 3),
 ('Sandra Bullock', 3),
 ('Chris Cooper', 3),
 ('Scott Glenn', 3),
 ('Danny Aiello', 3),
 ('Ziyi Zhang', 3),
 ('Eddie Murphy', 3),
 ('Mark Wahlberg', 3),
 ('Jennifer Lawrence', 3),
 ('Bruce Campbell', 3),
 ('Pen\\xe9lope Cruz', 3),
 ('Ryan Gosling', 3),
 ('Kathy Bates', 3),
 ('Samantha Morton', 3),
 ('Leslie Nielsen', 3),
 ('James McAvoy', 3),
 ('Danny Glover', 3),
 ('Dakota Fanning', 3),
 ('Marion Cotillard', 3),
 ('Anna Kendrick', 3),
 ('Forest Whitaker', 3),
 ('Patricia Clarkson', 3),
 ('Patrick Wilson', 3),
 ('Christopher Eccleston', 3),
 ('Paul Giamatti', 3),
 ('Michael Cera', 3),
 ('Barbara Hershey', 3),
 ('James Caan', 2),
 ('Heath Ledger', 2),
 ('Aaron Eckhart', 2),
 ('Lee J. Cobb', 2),
 ('Lee Van Cleef', 2),
 ('Orlando Bloom', 2),
 ('Ellen Page', 2),
 ('Gary Sinise', 2),
 ('Takashi Shimura', 2),
 ('Ray Liotta', 2),
 ('Laurence Fishburne', 2),
 ('Carrie-Anne Moss', 2),
 ('Gabriel Byrne', 2),
 ('Roberto Benigni', 2),
 ('Claudia Cardinale', 2),
 ('Jean Reno', 2),
 ('Suzanne Pleshette', 2),
 ('Fran\\xe7ois Cluzet', 2),
 ('Edward Furlong', 2),
 ('Paulette Goddard', 2),
 ('Tom Sizemore', 2),
 ('Karen Allen', 2),
 ('David Morse', 2),
 ('Adrien Brody', 2),
 ('Tom Hardy', 2),
 ('Linda Hamilton', 2),
 ('Joe Pantoliano', 2),
 ('George C. Scott', 2),
 ('Sterling Hayden', 2),
 ('Martin Sheen', 2),
 ('Lea Thompson', 2),
 ('James Earl Jones', 2),
 ('Ulrich M\\xfche', 2),
 ('Sebastian Koch', 2),
 ('Tom Skerritt', 2),
 ('John Hurt', 2),
 ('Kirk Douglas', 2),
 ('Thora Birch', 2),
 ('Audrey Tautou', 2),
 ('James Mason', 2),
 ('Fred MacMurray', 2),
 ('Edward G. Robinson', 2),
 ('Joan Cusack', 2),
 ('Patrick McGoohan', 2),
 ('Ellen Burstyn', 2),
 ("Peter O'Toole", 2),
 ('Alec Guinness', 2),
 ('Anthony Quinn', 2),
 ('Patrick Magee', 2),
 ('Tom Wilkinson', 2),
 ('Cybill Shepherd', 2),
 ('Kajol', 2),
 ('Bette Davis', 2),
 ('Anne Baxter', 2),
 ('George Sanders', 2),
 ('Tatsuya Nakadai', 2),
 ('F. Murray Abraham', 2),
 ('Tom Hulce', 2),
 ('Graham Chapman', 2),
 ('Eric Idle', 2),
 ('Gian Maria Volont\\xe9', 2),
 ('Diane Kruger', 2),
 ('Jean Arthur', 2),
 ('Claude Rains', 2),
 ('Don Rickles', 2),
 ('James Garner', 2),
 ('Thomas Bo Larsen', 2),
 ('Karl Malden', 2),
 ('Bibi Andersson', 2),
 ('Burt Lancaster', 2),
 ('Max von Sydow', 2),
 ('Ricardo Dar\\xedn', 2),
 ('Clark Gable', 2),
 ('Nick Nolte', 2),
 ('Joel Edgerton', 2),
 ('Anne Bancroft', 2),
 ('Hugo Weaving', 2),
 ('Dar\\xedo Grandinetti', 2),
 ('Sharon Stone', 2),
 ('Vivien Leigh', 2),
 ('Thomas Mitchell', 2),
 ('Dana Andrews', 2),
 ('Jay Baruchel', 2),
 ('Christopher Mintz-Plasse', 2),
 ('Daniel Br\\xfchl', 2),
 ('Eric Bana', 2),
 ('Ewen Bremner', 2),
 ('Bin Won', 2),
 ('Steve Buscemi', 2),
 ('Chris Evans', 2),
 ('Katharine Ross', 2),
 ('Haley Joel Osment', 2),
 ('Charlie Sheen', 2),
 ('Vin Diesel', 2),
 ('David Carradine', 2),
 ('Michael Fassbender', 2),
 ('Marcello Mastroianni', 2),
 ('Anouk Aim\\xe9e', 2),
 ('Matthew Goode', 2),
 ('Andy Lau', 2),
 ('Ciar\\xe1n Hinds', 2),
 ('Mathieu Amalric', 2),
 ('Mickey Rourke', 2),
 ('Kang-ho Song', 2),
 ('Mary McDonnell', 2),
 ('Elizabeth Taylor', 2),
 ('Farley Granger', 2),
 ('Takeshi Kaneshiro', 2),
 ('Shelley Winters', 2),
 ('Vincent Cassel', 2),
 ('Hubert Kound\\xe9', 2),
 ('Donnie Yen', 2),
 ('Wagner Moura', 2),
 ('Andr\\xe9 Ramiro', 2),
 ('Ulrich Thomsen', 2),
 ('Emily Mortimer', 2),
 ("Ryan O'Neal", 2),
 ('Jean-Louis Trintignant', 2),
 ('Maggie Cheung', 2),
 ('Raymond Massey', 2),
 ('Lee Remick', 2),
 ('Ben Gazzara', 2),
 ('Emma Stone', 2),
 ('Viola Davis', 2),
 ('Octavia Spencer', 2),
 ('Bel\\xe9n Rueda', 2),
 ('Lola Due\\xf1as', 2),
 ('Madeleine Stowe', 2),
 ('Iko Uwais', 2),
 ('Sylvester Stallone', 2),
 ('Andie MacDowell', 2),
 ('Billy Crystal', 2),
 ('Logan Lerman', 2),
 ('Ezra Miller', 2),
 ('Ruth Gordon', 2),
 ('Kim Hunter', 2),
 ('Ralph Bellamy', 2),
 ('Dwight Yoakam', 2),
 ('Ernest Borgnine', 2),
 ('Robert Ryan', 2),
 ('Sam Neill', 2),
 ('Jeff Goldblum', 2),
 ('Paul Bettany', 2),
 ('Paul Walker', 2),
 ("Catherine O'Hara", 2),
 ('James Dean', 2),
 ('Djimon Hounsou', 2),
 ('Albert Finney', 2),
 ('Billy Crudup', 2),
 ('Freida Pinto', 2),
 ('Chris Pine', 2),
 ('Zachary Quinto', 2),
 ('Richard Farnsworth', 2),
 ('Martin Landau', 2),
 ('Javier C\\xe1mara', 2),
 ('Sidney Poitier', 2),
 ('Warren Oates', 2),
 ('Geraldine Chaplin', 2),
 ('Jennifer Garner', 2),
 ('Julie Andrews', 2),
 ('Colin Clive', 2),
 ('Boris Karloff', 2),
 ('B\\xe9r\\xe9nice Bejo', 2),
 ('Juliette Binoche', 2),
 ('Zbigniew Zamachowski', 2),
 ('Christian Slater', 2),
 ('Justin Theroux', 2),
 ('Craig T. Nelson', 2),
 ('Colin Farrell', 2),
 ('Brendan Gleeson', 2),
 ('Jennifer Aniston', 2),
 ('Jon Voight', 2),
 ('John Belushi', 2),
 ('Emily Blunt', 2),
 ('Zach Galifianakis', 2),
 ('Will Smith', 2),
 ('Thandie Newton', 2),
 ('Jet Li', 2),
 ('Marisa Tomei', 2),
 ('Evan Rachel Wood', 2),
 ('Marisa Paredes', 2),
 ('Tahar Rahim', 2),
 ('Zoe Saldana', 2),
 ('Gwyneth Paltrow', 2),
 ('Yul Brynner', 2),
 ('Jamie Lee Curtis', 2),
 ('Greg Kinnear', 2),
 ('Burt Reynolds', 2),
 ("Brian O'Halloran", 2),
 ('Jeff Anderson', 2),
 ('Donald Sutherland', 2),
 ('Jim Sturgess', 2),
 ('Kenneth Branagh', 2),
 ('Ron Livingston', 2),
 ('Patricia Neal', 2),
 ('Jean-Claude Donda', 2),
 ('Eduardo Noriega', 2),
 ('Carey Mulligan', 2),
 ('Bryan Cranston', 2),
 ('Will Ferrell', 2),
 ('Asa Butterfield', 2),
 ('Miranda Richardson', 2),
 ('Bill Nighy', 2),
 ('Tilda Swinton', 2),
 ('Natalie Wood', 2),
 ('John C. Reilly', 2),
 ('Matthew Macfadyen', 2),
 ('Moritz Bleibtreu', 2),
 ('Joan Chen', 2),
 ('Sean Astin', 2),
 ('Josh Hartnett', 2),
 ('Jesse Eisenberg', 2),
 ('Andrew Garfield', 2),
 ('Deborah Kara Unger', 2),
 ('Angelina Jolie', 2),
 ('Juliette Lewis', 2),
 ('Naomie Harris', 2),
 ('Ned Beatty', 2),
 ('Helen Hunt', 2),
 ('Julie Kavner', 2),
 ('Jim Caviezel', 2),
 ('Richard Harris', 2),
 ('Jeff Daniels', 2),
 ('Chlo\\xeb Grace Moretz', 2),
 ('Judy Davis', 2),
 ('Elisabeth Shue', 2),
 ('Peter Dinklage', 2),
 ('Woody Harrelson', 2),
 ('Casey Affleck', 2),
 ('Keri Russell', 2),
 ('Andy Serkis', 2),
 ('Barry Pepper', 2),
 ('Armin Mueller-Stahl', 2),
 ('Michelle Williams', 2),
 ('Teri Garr', 2),
 ('Jonathan Rhys Meyers', 2),
 ('Hugh Grant', 2),
 ('John Getz', 2),
 ('Glenn Close', 2),
 ('Hayden Christensen', 2),
 ('Rosanna Arquette', 2),
 ('Verna Bloom', 2),
 ('Michelle Monaghan', 2),
 ('John Leguizamo', 2),
 ('Christopher Lee', 2),
 ('Rosario Dawson', 2),
 ('James Franco', 2),
 ('Jessica Tandy', 2),
 ('Cillian Murphy', 2),
 ('Phil Harris', 2),
 ('Cameron Bright', 2),
 ('Maria Bello', 2),
 ('Antonio Banderas', 2),
 ('Fionnula Flanagan', 2),
 ('Peter Sarsgaard', 2),
 ('Jada Pinkett Smith', 2),
 ('Chevy Chase', 2),
 ('David Strathairn', 2),
 ('Jennifer Tilly', 2),
 ('Halle Berry', 2),
 ('Geena Davis', 2),
 ('Christina Ricci', 2),
 ('Charlize Theron', 2),
 ('Lukas Haas', 2),
 ('Bob Gunton', 1),
 ('John Travolta', 1),
 ('Martin Balsam', 1),
 ('Eli Wallach', 1),
 ('Louise Fletcher', 1),
 ('Michael Berryman', 1),
 ('Keiko Tsushima', 1),
 ('Alexandre Rodrigues', 1),
 ('Matheus Nachtergaele', 1),
 ('Leandro Firmino', 1),
 ('Donna Reed', 1),
 ('Lionel Barrymore', 1),
 ('Nicoletta Braschi', 1),
 ('Giorgio Cantarini', 1),
 ('Lawrence A. Bonney', 1),
 ('Virginia Cherrill', 1),
 ('Florence Lee', 1),
 ('Daveigh Chase', 1),
 ('Miyu Irino', 1),
 ('Omar Sy', 1),
 ('Anne Le Ny', 1),
 ('Paul Henreid', 1),
 ('Miles Teller', 1),
 ('J.K. Simmons', 1),
 ('Melissa Benoist', 1),
 ('Henry Bergman', 1),
 ('Paul Freeman', 1),
 ('Wendell Corey', 1),
 ('Anthony Perkins', 1),
 ('Michael Clarke Duncan', 1),
 ('Gloria Swanson', 1),
 ('Erich von Stroheim', 1),
 ('Thomas Kretschmann', 1),
 ('Frank Finlay', 1),
 ('Connie Nielsen', 1),
 ('Darsheel Safary', 1),
 ('Tanay Chheda', 1),
 ('Philippe Noiret', 1),
 ('Enzo Cannavale', 1),
 ('Antonella Attili', 1),
 ('Jack Oakie', 1),
 ('Martina Gedeck', 1),
 ('Ralph Meeker', 1),
 ('Adolphe Menjou', 1),
 ('Christoph Waltz', 1),
 ('Madhavan', 1),
 ('Mona Singh', 1),
 ('Tsutomu Tatsumi', 1),
 ('Ayano Shiraishi', 1),
 ('Akemi Yamaguchi', 1),
 ('Shelley Duvall', 1),
 ('Danny Lloyd', 1),
 ('Peter Lorre', 1),
 ('Ellen Widmann', 1),
 ('Inge Landgut', 1),
 ('Ben Burtt', 1),
 ('Elissa Knight', 1),
 ('Jeff Garlin', 1),
 ('Tyrone Power', 1),
 ('Marlene Dietrich', 1),
 ('Charles Laughton', 1),
 ('Sunil Dutt', 1),
 ('Sanjay Dutt', 1),
 ('Arshad Warsi', 1),
 ('Annette Bening', 1),
 ('J\\xfcrgen Prochnow', 1),
 ('Herbert Gr\\xf6nemeyer', 1),
 ('Klaus Wennemann', 1),
 ('Y\\xf4ji Matsuda', 1),
 ('Yuriko Ishida', 1),
 ('Y\\xfbko Tanaka', 1),
 ('Mathieu Kassovitz', 1),
 ('Rufus', 1),
 ('Eva Marie Saint', 1),
 ('Soha Ali Khan', 1),
 ('Siddharth', 1),
 ('Peyman Moaadi', 1),
 ('Leila Hatami', 1),
 ('Sareh Bayat', 1),
 ('Dorothy Comingore', 1),
 ('Carrie Henn', 1),
 ('Kim Novak', 1),
 ('Barbara Bel Geddes', 1),
 ('Ji-tae Yu', 1),
 ('Hye-jeong Kang', 1),
 ('James Woods', 1),
 ('Elizabeth McGovern', 1),
 ('Barbara Stanwyck', 1),
 ('Sophie Marceau', 1),
 ('John Megna', 1),
 ('Frank Overton', 1),
 ('Malcolm McDowell', 1),
 ('Michael Bates', 1),
 ('Lamberto Maggiorani', 1),
 ('Enzo Staiola', 1),
 ('Lianella Carell', 1),
 ('Edna Purviance', 1),
 ('Jackie Coogan', 1),
 ('Gayatri Joshi', 1),
 ('Kishori Balal', 1),
 ('Amrish Puri', 1),
 ('Gene Kelly', 1),
 ("Donald O'Connor", 1),
 ('Debbie Reynolds', 1),
 ('Eijir\\xf4 T\\xf4no', 1),
 ('Machiko Ky\\xf4', 1),
 ('Masayuki Mori', 1),
 ('Elizabeth Berridge', 1),
 ('Walter Huston', 1),
 ('Tim Holt', 1),
 ('Matthew Modine', 1),
 ('R. Lee Ermey', 1),
 ("Vincent D'Onofrio", 1),
 ('Nobuo Kaneko', 1),
 ("Shin'ichi Himori", 1),
 ('Alida Valli', 1),
 ('Jason Statham', 1),
 ('Brigitte Helm', 1),
 ('Alfred Abel', 1),
 ('Gustav Fr\\xf6hlich', 1),
 ('Saif Ali Khan', 1),
 ('Akshaye Khanna', 1),
 ('Keir Dullea', 1),
 ('Gary Lockwood', 1),
 ('William Sylvester', 1),
 ('Marilyn Monroe', 1),
 ('Tony Curtis', 1),
 ('Eli Roth', 1),
 ('Steven Bauer', 1),
 ('Alison Doody', 1),
 ('Richard Attenborough', 1),
 ('Annika Wedderkopp', 1),
 ('Buster Keaton', 1),
 ('Marion Mack', 1),
 ('Glen Cavender', 1),
 ('Cathy Moriarty', 1),
 ('Alexandra Maria Lara', 1),
 ('Ulrich Matthes', 1),
 ('Edward Asner', 1),
 ('Jordan Nagai', 1),
 ('John Ratzenberger', 1),
 ('Victor Sj\\xf6str\\xf6m', 1),
 ('Ingrid Thulin', 1),
 ('Mack Swain', 1),
 ('Tom Murray', 1),
 ('Akira Terao', 1),
 ('Jinpachi Nezu', 1),
 ('John Huston', 1),
 ('Hitoshi Takagi', 1),
 ('Noriko Hidaka', 1),
 ('Chika Sakamoto', 1),
 ('Richard Widmark', 1),
 ('Ranbir Kapoor', 1),
 ('Priyanka Chopra', 1),
 ('Ileana', 1),
 ('Gunnar Bj\\xf6rnstrand', 1),
 ('Bengt Ekerot', 1),
 ('Ivana Baquero', 1),
 ('Ariadna Gil', 1),
 ('Sergi L\\xf3pez', 1),
 ('Bonnie Bedelia', 1),
 ('Yves Montand', 1),
 ('Charles Vanel', 1),
 ('Peter van Eyck', 1),
 ('Soledad Villamil', 1),
 ('Pablo Rago', 1),
 ('Gracy Singh', 1),
 ('Rachel Shelley', 1),
 ('Margot Robbie', 1),
 ('Claudette Colbert', 1),
 ('Walter Connolly', 1),
 ('Rutger Hauer', 1),
 ('Sean Young', 1),
 ('Chieko Baish\\xf4', 1),
 ('Takuya Kimura', 1),
 ('Tatsuya Gash\\xfbin', 1),
 ('Joan Fontaine', 1),
 ('Lubna Azabal', 1),
 ('M\\xe9lissa D\\xe9sormeaux-Poulin', 1),
 ('Maxim Gaudette', 1),
 ('Jason Flemyng', 1),
 ('Dexter Fletcher', 1),
 ('Nick Moran', 1),
 ('Rupert Graves', 1),
 ('George Kennedy', 1),
 ('Strother Martin', 1),
 ('Mar\\xeda Marull', 1),
 ('M\\xf3nica Villa', 1),
 ('Rosamund Pike', 1),
 ('Neil Patrick Harris', 1),
 ('Fredric March', 1),
 ('Myrna Loy', 1),
 ('Simone Signoret', 1),
 ('V\\xe9ra Clouzot', 1),
 ('Paul Meurisse', 1),
 ('Bee Vang', 1),
 ('Christopher Carley', 1),
 ('Chris Hemsworth', 1),
 ('Olivia Wilde', 1),
 ('Vince Vaughn', 1),
 ('Tae-hyun Cha', 1),
 ('Gianna Jun', 1),
 ('In-mun Kim', 1),
 ('Cary-Hiroyuki Tagawa', 1),
 ('Mary Astor', 1),
 ('Gladys George', 1),
 ('Ray Milland', 1),
 ('Robert Cummings', 1),
 ('Jonny Lee Miller', 1),
 ('Dong-gun Jang', 1),
 ('Eun-ju Lee', 1),
 ('Liv Ullmann', 1),
 ('Margaretha Krook', 1),
 ('William H. Macy', 1),
 ('Jean-Pierre L\\xe9aud', 1),
 ('Albert R\\xe9my', 1),
 ('Claire Maurier', 1),
 ('Mandy Patinkin', 1),
 ('Sophie Okonedo', 1),
 ('Alisa Freyndlikh', 1),
 ('Aleksandr Kaydanovskiy', 1),
 ('Anatoliy Solonitsyn', 1),
 ('Brahim Hadjadj', 1),
 ('Jean Martin', 1),
 ('Yacef Saadi', 1),
 ('Predrag Manojlovic', 1),
 ('Lazar Ristovski', 1),
 ('Mirjana Jokovic', 1),
 ('Bertil Guve', 1),
 ('Pernilla Allwin', 1),
 ('Kristina Adolphson', 1),
 ('Peter Finch', 1),
 ('Wilford Brimley', 1),
 ('Keith David', 1),
 ('Jane Darwell', 1),
 ('John Carradine', 1),
 ('Bajram Severdzan', 1),
 ('Srdjan Todorovic', 1),
 ('Branka Katic', 1),
 ('Michael Palin', 1),
 ('Albert Brooks', 1),
 ('Ellen DeGeneres', 1),
 ('Alexander Gould', 1),
 ('Sumi Shimamoto', 1),
 ('Mahito Tsujimura', 1),
 ('Hisako Ky\\xf4da', 1),
 ('Taron Egerton', 1),
 ('Tom Berenger', 1),
 ('Pete Postlethwaite', 1),
 ('Alison Crosbie', 1),
 ('Daryl Hannah', 1),
 ('Alain Delon', 1),
 ('Nathalie Delon', 1),
 ('Fran\\xe7ois P\\xe9rier', 1),
 ('Michael Kenneth Williams', 1),
 ('Pruitt Taylor Vince', 1),
 ('Bill Nunn', 1),
 ('Stephen Boyd', 1),
 ('Emilio Echevarr\\xeda', 1),
 ('Goya Toledo', 1),
 ('Wil Wheaton', 1),
 ('River Phoenix', 1),
 ('Corey Feldman', 1),
 ('Joan Crawford', 1),
 ('Victor Buono', 1),
 ('Tony Roberts', 1),
 ('Benedict Cumberbatch', 1),
 ('Gene Tierney', 1),
 ('Clifton Webb', 1),
 ('Masahiro Motoki', 1),
 ('Ry\\xf4ko Hirosue', 1),
 ('Tsutomu Yamazaki', 1),
 ('Anthony Chau-Sang Wong', 1),
 ('Paul Dano', 1),
 ('Giulietta Masina', 1),
 ('Richard Basehart', 1),
 ('Sang-kyung Kim', 1),
 ('Roe-ha Kim', 1),
 ('Jena Malone', 1),
 ('George Segal', 1),
 ('John Gielgud', 1),
 ('Candice Bergen', 1),
 ('Natalya Bondarchuk', 1),
 ('Donatas Banionis', 1),
 ('J\\xfcri J\\xe4rvet', 1),
 ('Harry Dean Stanton', 1),
 ('Nastassja Kinski', 1),
 ('Dean Stockwell', 1),
 ('Judy Garland', 1),
 ('Frank Morgan', 1),
 ('Ray Bolger', 1),
 ('Seung-yeon Lee', 1),
 ('Hyun-kyoon Lee', 1),
 ('Hyuk-ho Kwon', 1),
 ('Ellar Coltrane', 1),
 ('Timothy Bottoms', 1),
 ('Robert Walker', 1),
 ('Ruth Roman', 1),
 ('Burl Ives', 1),
 ('Anita Ekberg', 1),
 ('Brigitte Lin', 1),
 ('Robert Mitchum', 1),
 ('Lillian Gish', 1),
 ('Sa\\xefd Taghmaoui', 1),
 ('Simon Yam', 1),
 ('Siu-Wong Fan', 1),
 ('Gary Cooper', 1),
 ('Andrea Eckert', 1),
 ('Irandhir Santos', 1),
 ('\\xc9dgar Ram\\xedrez', 1),
 ('Anna Paquin', 1),
 ('James Van Der Beek', 1),
 ('Cloris Leachman', 1),
 ('Henning Moritzen', 1),
 ('Ki-duk Kim', 1),
 ('Yeong-su Oh', 1),
 ('Jong-ho Kim', 1),
 ('Marisa Berenson', 1),
 ('Don Taylor', 1),
 ('Otto Preminger', 1),
 ('Ir\\xe8ne Jacob', 1),
 ('Fr\\xe9d\\xe9rique Feder', 1),
 ('Alec Cawthorne', 1),
 ('Ping Lam Siu', 1),
 ('Priscilla Lane', 1),
 ('John Ridgely', 1),
 ('Eddie Albert', 1),
 ('Nozomu Sasaki', 1),
 ('Mami Koyama', 1),
 ('Mitsuo Iwata', 1),
 ('Werner Krauss', 1),
 ('Conrad Veidt', 1),
 ('Friedrich Feher', 1),
 ('Caio Junqueira', 1),
 ('Jackie Gleason', 1),
 ('Piper Laurie', 1),
 ('Dean Martin', 1),
 ('Ricky Nelson', 1),
 ('Josephine Hull', 1),
 ('Peggy Dow', 1),
 ('Peter Billingsley', 1),
 ('Melinda Dillon', 1),
 ('Darren McGavin', 1),
 ('Yayan Ruhian', 1),

In [ ]:
#@title Consigue el Token para corregir el ejercicio en Nodd3r
import hashlib

correct = str(solucion_1)+str(solucion_1b)+str(solucion_2)+str(solucion_3)+str(solucion_4)+str(solucion_5)+str(solucion_6)+str(solucion_7)
pwd = hashlib.sha256(str(correct).encode())
#print('El token para corregir en Nodd3r es:\n',pwd.hexdigest())
if pwd.hexdigest()[0:6] == '430f84':
  print('¡Felicidades! puedes avanzar al siguiente modulo \n El token es: ',pwd.hexdigest())
else:
  print('Hay algún error en el código o tu forma es diferente a la planteada, pregunta por el foro si no lo ves claro.')

¡Felicidades! puedes avanzar al siguiente modulo
 El token es:  430f84514562dd6d6d954ed4433273bdbf0ee8d812a9edc646063292c7837cc4